version: '3.0'
    
services:
    web:
        image: 'tiendas-php'
        ports:
            - '8000:8000'
        volumes:
            - "./:/app"
        command: php artisan serve --host=0.0.0.0

    mysql:
        image: 'mysql:5.7'
        ports:
            - '3307:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=toor
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data: